name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Free disk pace
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@support-building-cog-from-source
        with:
          cog-commitish: "3cf1e44"
          install-cuda: false
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Build with Cog
        run: |
          set -x
          pwd
          ls -al
          echo $PATH
          cog build

      - name: Push to Replicate
        run: |
          cog push r8.im/zeke/hello-world