name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Cog
        uses: replicate/setup-cog@b152ebfd62eecd5d256c3087a9e1a1aae9d4855c
        with:
          cog-commitish: "3cf1e44"
          install-cuda: false
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Cog
        run: |
          cog build

      - name: Push to Replicate
        run: |
          cog push r8.im/zeke/hello-world